//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 06:57:52 PM BRT 
//


package br.ipt.servico.relevancia.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.ipt.servico.relevancia.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Process_QNAME = new QName("http://schemas.xmlsoap.org/ws/2003/03/business-process/", "process");
    private final static QName _Definitions_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "definitions");
    private final static QName _From_QNAME = new QName("http://schemas.xmlsoap.org/ws/2003/03/business-process/", "from");
    private final static QName _TOperationOutput_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "output");
    private final static QName _TOperationFault_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "fault");
    private final static QName _TOperationInput_QNAME = new QName("http://schemas.xmlsoap.org/wsdl/", "input");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.ipt.servico.relevancia.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TFrom }
     * 
     */
    public TFrom createTFrom() {
        return new TFrom();
    }

    /**
     * Create an instance of {@link TCopy }
     * 
     */
    public TCopy createTCopy() {
        return new TCopy();
    }

    /**
     * Create an instance of {@link TReply }
     * 
     */
    public TReply createTReply() {
        return new TReply();
    }

    /**
     * Create an instance of {@link TCorrelationWithPattern }
     * 
     */
    public TCorrelationWithPattern createTCorrelationWithPattern() {
        return new TCorrelationWithPattern();
    }

    /**
     * Create an instance of {@link TCatch }
     * 
     */
    public TCatch createTCatch() {
        return new TCatch();
    }

    /**
     * Create an instance of {@link TActivityOrCompensateContainer }
     * 
     */
    public TActivityOrCompensateContainer createTActivityOrCompensateContainer() {
        return new TActivityOrCompensateContainer();
    }

    /**
     * Create an instance of {@link TPartners }
     * 
     */
    public TPartners createTPartners() {
        return new TPartners();
    }

    /**
     * Create an instance of {@link TTypes }
     * 
     */
    public TTypes createTTypes() {
        return new TTypes();
    }

    /**
     * Create an instance of {@link TPortType }
     * 
     */
    public TPortType createTPortType() {
        return new TPortType();
    }

    /**
     * Create an instance of {@link TCorrelationsWithPattern }
     * 
     */
    public TCorrelationsWithPattern createTCorrelationsWithPattern() {
        return new TCorrelationsWithPattern();
    }

    /**
     * Create an instance of {@link TParam }
     * 
     */
    public TParam createTParam() {
        return new TParam();
    }

    /**
     * Create an instance of {@link TReceive }
     * 
     */
    public TReceive createTReceive() {
        return new TReceive();
    }

    /**
     * Create an instance of {@link TCompensationHandler }
     * 
     */
    public TCompensationHandler createTCompensationHandler() {
        return new TCompensationHandler();
    }

    /**
     * Create an instance of {@link TActivity }
     * 
     */
    public TActivity createTActivity() {
        return new TActivity();
    }

    /**
     * Create an instance of {@link TCorrelationSets }
     * 
     */
    public TCorrelationSets createTCorrelationSets() {
        return new TCorrelationSets();
    }

    /**
     * Create an instance of {@link TPart }
     * 
     */
    public TPart createTPart() {
        return new TPart();
    }

    /**
     * Create an instance of {@link TBindingOperationFault }
     * 
     */
    public TBindingOperationFault createTBindingOperationFault() {
        return new TBindingOperationFault();
    }

    /**
     * Create an instance of {@link TBindingOperation }
     * 
     */
    public TBindingOperation createTBindingOperation() {
        return new TBindingOperation();
    }

    /**
     * Create an instance of {@link TVariable }
     * 
     */
    public TVariable createTVariable() {
        return new TVariable();
    }

    /**
     * Create an instance of {@link TEventHandlers }
     * 
     */
    public TEventHandlers createTEventHandlers() {
        return new TEventHandlers();
    }

    /**
     * Create an instance of {@link TAssign }
     * 
     */
    public TAssign createTAssign() {
        return new TAssign();
    }

    /**
     * Create an instance of {@link TService }
     * 
     */
    public TService createTService() {
        return new TService();
    }

    /**
     * Create an instance of {@link TProcess }
     * 
     */
    public TProcess createTProcess() {
        return new TProcess();
    }

    /**
     * Create an instance of {@link TPartnerLink }
     * 
     */
    public TPartnerLink createTPartnerLink() {
        return new TPartnerLink();
    }

    /**
     * Create an instance of {@link TPick }
     * 
     */
    public TPick createTPick() {
        return new TPick();
    }

    /**
     * Create an instance of {@link TThrow }
     * 
     */
    public TThrow createTThrow() {
        return new TThrow();
    }

    /**
     * Create an instance of {@link TSequence }
     * 
     */
    public TSequence createTSequence() {
        return new TSequence();
    }

    /**
     * Create an instance of {@link TScope }
     * 
     */
    public TScope createTScope() {
        return new TScope();
    }

    /**
     * Create an instance of {@link TPartner }
     * 
     */
    public TPartner createTPartner() {
        return new TPartner();
    }

    /**
     * Create an instance of {@link TMessage }
     * 
     */
    public TMessage createTMessage() {
        return new TMessage();
    }

    /**
     * Create an instance of {@link TLinks }
     * 
     */
    public TLinks createTLinks() {
        return new TLinks();
    }

    /**
     * Create an instance of {@link TOperation }
     * 
     */
    public TOperation createTOperation() {
        return new TOperation();
    }

    /**
     * Create an instance of {@link TTarget }
     * 
     */
    public TTarget createTTarget() {
        return new TTarget();
    }

    /**
     * Create an instance of {@link TActivityContainer }
     * 
     */
    public TActivityContainer createTActivityContainer() {
        return new TActivityContainer();
    }

    /**
     * Create an instance of {@link TSwitch }
     * 
     */
    public TSwitch createTSwitch() {
        return new TSwitch();
    }

    /**
     * Create an instance of {@link TPartner.PartnerLink }
     * 
     */
    public TPartner.PartnerLink createTPartnerPartnerLink() {
        return new TPartner.PartnerLink();
    }

    /**
     * Create an instance of {@link TFlow }
     * 
     */
    public TFlow createTFlow() {
        return new TFlow();
    }

    /**
     * Create an instance of {@link TWait }
     * 
     */
    public TWait createTWait() {
        return new TWait();
    }

    /**
     * Create an instance of {@link TSwitch.Case }
     * 
     */
    public TSwitch.Case createTSwitchCase() {
        return new TSwitch.Case();
    }

    /**
     * Create an instance of {@link TFault }
     * 
     */
    public TFault createTFault() {
        return new TFault();
    }

    /**
     * Create an instance of {@link TInvoke }
     * 
     */
    public TInvoke createTInvoke() {
        return new TInvoke();
    }

    /**
     * Create an instance of {@link TBinding }
     * 
     */
    public TBinding createTBinding() {
        return new TBinding();
    }

    /**
     * Create an instance of {@link TVariables }
     * 
     */
    public TVariables createTVariables() {
        return new TVariables();
    }

    /**
     * Create an instance of {@link TOnMessage }
     * 
     */
    public TOnMessage createTOnMessage() {
        return new TOnMessage();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link TWhile }
     * 
     */
    public TWhile createTWhile() {
        return new TWhile();
    }

    /**
     * Create an instance of {@link TPort }
     * 
     */
    public TPort createTPort() {
        return new TPort();
    }

    /**
     * Create an instance of {@link TDocumentation }
     * 
     */
    public TDocumentation createTDocumentation() {
        return new TDocumentation();
    }

    /**
     * Create an instance of {@link TSource }
     * 
     */
    public TSource createTSource() {
        return new TSource();
    }

    /**
     * Create an instance of {@link TEmpty }
     * 
     */
    public TEmpty createTEmpty() {
        return new TEmpty();
    }

    /**
     * Create an instance of {@link TOnAlarm }
     * 
     */
    public TOnAlarm createTOnAlarm() {
        return new TOnAlarm();
    }

    /**
     * Create an instance of {@link TCorrelations }
     * 
     */
    public TCorrelations createTCorrelations() {
        return new TCorrelations();
    }

    /**
     * Create an instance of {@link TBindingOperationMessage }
     * 
     */
    public TBindingOperationMessage createTBindingOperationMessage() {
        return new TBindingOperationMessage();
    }

    /**
     * Create an instance of {@link TCompensate }
     * 
     */
    public TCompensate createTCompensate() {
        return new TCompensate();
    }

    /**
     * Create an instance of {@link TLink }
     * 
     */
    public TLink createTLink() {
        return new TLink();
    }

    /**
     * Create an instance of {@link TExtensibleElements }
     * 
     */
    public TExtensibleElements createTExtensibleElements() {
        return new TExtensibleElements();
    }

    /**
     * Create an instance of {@link TPartnerLinks }
     * 
     */
    public TPartnerLinks createTPartnerLinks() {
        return new TPartnerLinks();
    }

    /**
     * Create an instance of {@link TDocumented }
     * 
     */
    public TDocumented createTDocumented() {
        return new TDocumented();
    }

    /**
     * Create an instance of {@link TCorrelation }
     * 
     */
    public TCorrelation createTCorrelation() {
        return new TCorrelation();
    }

    /**
     * Create an instance of {@link TImport }
     * 
     */
    public TImport createTImport() {
        return new TImport();
    }

    /**
     * Create an instance of {@link TCorrelationSet }
     * 
     */
    public TCorrelationSet createTCorrelationSet() {
        return new TCorrelationSet();
    }

    /**
     * Create an instance of {@link TFaultHandlers }
     * 
     */
    public TFaultHandlers createTFaultHandlers() {
        return new TFaultHandlers();
    }

    /**
     * Create an instance of {@link TDefinitions }
     * 
     */
    public TDefinitions createTDefinitions() {
        return new TDefinitions();
    }

    /**
     * Create an instance of {@link TTerminate }
     * 
     */
    public TTerminate createTTerminate() {
        return new TTerminate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2003/03/business-process/", name = "process")
    public JAXBElement<TProcess> createProcess(TProcess value) {
        return new JAXBElement<TProcess>(_Process_QNAME, TProcess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "definitions")
    public JAXBElement<TDefinitions> createDefinitions(TDefinitions value) {
        return new JAXBElement<TDefinitions>(_Definitions_QNAME, TDefinitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFrom }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2003/03/business-process/", name = "from")
    public JAXBElement<TFrom> createFrom(TFrom value) {
        return new JAXBElement<TFrom>(_From_QNAME, TFrom.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParam }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "output", scope = TOperation.class)
    public JAXBElement<TParam> createTOperationOutput(TParam value) {
        return new JAXBElement<TParam>(_TOperationOutput_QNAME, TParam.class, TOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "fault", scope = TOperation.class)
    public JAXBElement<TFault> createTOperationFault(TFault value) {
        return new JAXBElement<TFault>(_TOperationFault_QNAME, TFault.class, TOperation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParam }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/wsdl/", name = "input", scope = TOperation.class)
    public JAXBElement<TParam> createTOperationInput(TParam value) {
        return new JAXBElement<TParam>(_TOperationInput_QNAME, TParam.class, TOperation.class, value);
    }

}
