//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 06:57:52 PM BRT 
//


package br.ipt.servico.relevancia.modelo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tFaultHandlers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tFaultHandlers">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="catch" type="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}tCatch" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="catchAll" type="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}tActivityOrCompensateContainer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tFaultHandlers", propOrder = {
    "_catch",
    "catchAll"
})
public class TFaultHandlers
    extends TExtensibleElements
{

    @XmlElement(name = "catch")
    protected List<TCatch> _catch;
    protected TActivityOrCompensateContainer catchAll;

    /**
     * Gets the value of the catch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCatch }
     * 
     * 
     */
    public List<TCatch> getCatch() {
        if (_catch == null) {
            _catch = new ArrayList<TCatch>();
        }
        return this._catch;
    }

    /**
     * Gets the value of the catchAll property.
     * 
     * @return
     *     possible object is
     *     {@link TActivityOrCompensateContainer }
     *     
     */
    public TActivityOrCompensateContainer getCatchAll() {
        return catchAll;
    }

    /**
     * Sets the value of the catchAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link TActivityOrCompensateContainer }
     *     
     */
    public void setCatchAll(TActivityOrCompensateContainer value) {
        this.catchAll = value;
    }

}
