//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 06:57:52 PM BRT 
//


package br.ipt.servico.relevancia.modelo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSequence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSequence">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}tActivity">
 *       &lt;sequence>
 *         &lt;group ref="{http://schemas.xmlsoap.org/ws/2003/03/business-process/}activity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSequence", propOrder = {
    "activity"
})
public class TSequence
    extends TActivity
{

    @XmlElements({
        @XmlElement(name = "switch", type = TSwitch.class),
        @XmlElement(name = "reply", type = TReply.class),
        @XmlElement(name = "sequence", type = TSequence.class),
        @XmlElement(name = "flow", type = TFlow.class),
        @XmlElement(name = "scope", type = TScope.class),
        @XmlElement(name = "wait", type = TWait.class),
        @XmlElement(name = "throw", type = TThrow.class),
        @XmlElement(name = "invoke", type = TInvoke.class),
        @XmlElement(name = "pick", type = TPick.class),
        @XmlElement(name = "receive", type = TReceive.class),
        @XmlElement(name = "assign", type = TAssign.class),
        @XmlElement(name = "terminate", type = TTerminate.class),
        @XmlElement(name = "while", type = TWhile.class),
        @XmlElement(name = "empty", type = TEmpty.class)
    })
    protected List<TActivity> activity;

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSwitch }
     * {@link TReply }
     * {@link TSequence }
     * {@link TFlow }
     * {@link TScope }
     * {@link TWait }
     * {@link TThrow }
     * {@link TInvoke }
     * {@link TPick }
     * {@link TReceive }
     * {@link TAssign }
     * {@link TTerminate }
     * {@link TWhile }
     * {@link TEmpty }
     * 
     * 
     */
    public List<TActivity> getActivity() {
        if (activity == null) {
            activity = new ArrayList<TActivity>();
        }
        return this.activity;
    }

}
